set -g default-terminal "screen-256color"

#set-option -g default-shell "/opt/homebrew/bin/bash"
#set-option -g default-command "/opt/homebrew/bin/bash"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind %
bind '\' split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on

source-file ~/.config/tmux/theme.conf
